Feature/watanabe 75 ui improvement
Piko-Piko-Pon-Taro/Remollege pull request #131
Opened 2020-09-21 05:26 UTC by tsuyoshi628

#75 
ぺちぺち見た目調整しておいた。

2020-09-21 05:30 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +      <v-card-actions v-if="$auth.loggedIn" @click="dialog = true">
@tomoino 
マウスホバー時に指マークにしたいんだけどいい方法知ってたりする？

2020-09-21 05:31 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +    <!-- sidebar? FIXME: 適切なコメントアウトに修正 -->
@tomoino 
ここのv-navigation-drawerってなんのやつだっけ？

2020-09-21 14:03 UTC, tomoino commented on client/layouts/default.vue
> +    <!-- sidebar? FIXME: 適切なコメントアウトに修正 -->
これは消し忘れなのでこっちで消してpushしときます

2020-09-21 14:05 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +    <!-- sidebar? FIXME: 適切なコメントアウトに修正 -->
おけ。

2020-09-21 14:11 UTC, tomoino commented on client/layouts/default.vue
> +      <v-card-actions v-if="$auth.loggedIn" @click="dialog = true">
style="cursor: pointer;"を使うのが一般的だと思う。
これも変更しておきます。

2020-09-21 14:18 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +      <v-card-actions v-if="$auth.loggedIn" @click="dialog = true">
あそうか普通にそのスタイル書けば良かっただけか。
なんか無駄にhoverのアクション取得して…とか考えてたわあほか。

2020-09-21 14:46 UTC, tsuyoshi628 commented
@tomoino 
あざす

2020-09-21 14:46 UTC, tomoino requested changes
一通り確認してコメントしたので確認・修正お願いします！

2020-09-21 14:46 UTC, tomoino commented on client/layouts/default.vue
> +      </p>
ユーザーの視点移動考えると、ヘッダーに各ページの案内入れるのは微妙な気がする…
レイアウトがpageコンテンツと密結合になるのも良くないから、各pagesの上部に入れる方が良いと思う

2020-09-21 14:46 UTC, tomoino commented on client/layouts/default.vue
> +      </p>
全部に言えるんだけど、背景色はconstで定義されている色を使ってほしいです
個別に指定するとまとめて変えられずに不便であったり、統一感なくなってしまったりする可能性があります

2020-09-21 14:46 UTC, tomoino commented on client/layouts/default.vue
> +      </v-tooltip>
tooltipを併用するとマウスを乗せたときに説明が出てきてくれるので良い感じ

2020-09-21 14:49 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +      </v-tooltip>
ほえー

2020-09-21 14:56 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +      </p>
たしかにすぎます。

2020-09-21 15:09 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +      </v-tooltip>
@tomoino 
あ、これスマホだとどうなるんやろね

2020-09-21 15:09 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +      </v-tooltip>
ま、ええか。

2020-09-21 15:10 UTC, tsuyoshi628 commented on client/layouts/default.vue
> +      </p>
hintコンポーネントを作ろうということですね。
しかしstorybookが起動できなくて困っています。🥺

2020-09-21 17:55 UTC, tsuyoshi628 commented
@tomoino 
パンくずリストにリンクはつけてないです。
なぜかstorybook立ち上げられなかったのでstorybookの挙動確認してないです。
見様見真似で書いたのでstorybook間違ってるかもしれないけどご愛嬌で🙇‍♂️。
あと、HintTextをatomsに、Breadcrumbをorganismsに入れたけど、間違ってたら教えて欲しいす。
よろしく🙆‍♂️

2020-09-22 04:28 UTC, tomoino approved these changes
修正点も全部確認済み
OK

2020-09-22 04:28 UTC, tomoino commented on client/components/atoms/HintText.vue
> +      defaul: null
default

2020-09-22 04:29 UTC, merged