buildingsテーブル追加
Piko-Piko-Pon-Taro/Remollege pull request #79
Opened 2020-09-02 11:18 UTC by turunasi

@tsuyoshi628 
こんなもんでどう？
methodはとりあえずgetAllBuildingsとgetOneBuildingのみ作った
動作確認済み

2020-09-04 11:53 UTC, turunasi commented
@tsuyoshi628 
paranoid追加したっぴよ＝＝＝＝＝

2020-09-04 12:35 UTC, tsuyoshi628 requested changes

2020-09-04 12:35 UTC, tsuyoshi628 commented on api/seeders/20200903010712-test-buildings.js
> +      { campusId:1, name:'63号館', createdAt:'2020-09-02 00:07:51', updatedAt:'2020-09-02 00:07:51'}
id,imgの追加をよろしくお願いいたします。

2020-09-04 12:35 UTC, tsuyoshi628 commented on api/seeders/20200903103902-test-rooms.js
> +      { buildingId:1, name:'立ち食いパスタ アッパーカット 56号館店', createdAt:'2020-09-02 00:15:20', updatedAt:'2020-09-02 00:15:20'}
id,imgの追加をよろしくお願いいたします。

2020-09-04 12:35 UTC, tsuyoshi628 commented on api/seeders/20200903103918-test-tables-users.js
> +      { tableId:4, userId:7, createdAt:'2020-08-15 00:00:00', updatedAt:'2020-08-15 00:00:00'}
これ一時的なデータだから消して大丈夫。

2020-09-04 12:35 UTC, tsuyoshi628 commented on api/seeders/20200903103927-test-chats.js
> +      { tableId:1, userId:1, content:'ヤサイマシマシニンニクマシマシアブラマシマシ', createdAt:'2020-08-14 17:10:08', updatedAt:'2020-08-14 17:10:08'}
idの追加をよろしくお願いいたします。

2020-09-04 12:35 UTC, tsuyoshi628 commented on api/seeders/20200903103932-test-tables.js
> +      { roomId:2, createdAt:'2020-08-15 00:00:00', updatedAt:'2020-08-15 00:00:00'}
idの追加をよろしくお願いいたします。

2020-09-04 12:35 UTC, tsuyoshi628 commented on api/seeders/20200903103937-test-users.js
> +      { name:'渡邉', email:'watanabe@gmail.com', password:'userpass', img:'sampleIcon3.jpg', createdAt:'2020-08-15 00:00:00', updatedAt:'2020-08-15 00:00:00'}
id, imgの追加をよろしくお願いします。

2020-09-04 12:35 UTC, tsuyoshi628 commented on database/init/db.sql
> +-- 生成日時: 2020 年 9 月 01 日 15:16
このファイル消してもええで

2020-09-05 11:48 UTC, tomoino commented
Usersにprofileカラム足してほしい！
あと、画像のパスをGCSのものにしてほしい！
https://console.cloud.google.com/storage/browser/remollege-storage;tab=objects?forceOnBucketsSortingFiltering=false&hl=ja&project=pikopikopon1&prefix=

2020-09-05 12:18 UTC, turunasi commented
> Usersにprofileカラム足してほしい！
> あと、画像のパスをGCSのものにしてほしい！
> https://console.cloud.google.com/storage/browser/remollege-storage;tab=objects?forceOnBucketsSortingFiltering=false&hl=ja&project=pikopikopon1&prefix=

カラムの詳細はどうする？VARCHAR(255)じゃなくてTEXTの方が良いよね,あとNULLを許容するカラムにする？

2020-09-05 12:21 UTC, tomoino commented
@turunasi TEXTの方が良いね。ログイン時点で何も入ってないことを想定しているので、NULL許容で良いと思う。

2020-09-06 12:40 UTC, tsuyoshi628 commented
@turunasi 
Usersテーブルに
google_sub varchar(255) null
を追加して欲しいっす。

2020-09-06 13:38 UTC, turunasi commented
@tomoino @tsuyoshi628 
対応したお

2020-09-06 13:50 UTC, tsuyoshi628 requested changes
どふぇ

2020-09-06 13:50 UTC, tsuyoshi628 commented on api/migrations/20200903103425-Users.js
> +      },
email重複してる

2020-09-06 13:50 UTC, tsuyoshi628 commented on api/seeders/20200903103937-test-users.js
> +};
こんな感じでpasswordハッシュ化してくれると助かる
```
'use strict';
const bcrypt = require('bcrypt');

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Users', [
      {
        id: 1,
        name: 'テスト アカウント',
        email: 'test@example.com',
        password: bcrypt.hashSync('testtest', bcrypt.genSaltSync(10)),
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        emailVerifiedAt: new Date()
      },
      {
        id: 2,
        name: '東 コウスケ',
        email: 'test.1@example.com',
        password: bcrypt.hashSync('dfoihqer9ltk', bcrypt.genSaltSync(10)),
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        emailVerifiedAt: new Date()
      },
      {
        id: 3,
        name: '井上 智裕',
        email: 'test.2@example.com',
        password: bcrypt.hashSync('345oivejao9', bcrypt.genSaltSync(10)),
        deletedAt: null,
        createdAt: new Date(),
        updatedAt: new Date(),
        emailVerifiedAt: new Date()
      }
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Users', null, {});
  }
};
```

2020-09-06 13:50 UTC, tsuyoshi628 commented on api/setup.sh
> +}
もしかしたら`npx sequelize-cli db:migrate`の前に一回`npx sequelize-cli db:migrate:undo:all`でmigration初期化する処理入れた方がいいかも

2020-09-06 14:10 UTC, turunasi commented on api/seeders/20200903103937-test-users.js
> +};
OK

2020-09-06 14:10 UTC, turunasi commented on api/migrations/20200903103425-Users.js
> +      },
OK

2020-09-06 14:10 UTC, turunasi commented on api/setup.sh
> +}
うんちでりゅ

2020-09-06 14:10 UTC, turunasi commented
@tsuyoshi628 
直したど

2020-09-06 14:10 UTC, turunasi commented
直したど

2020-09-06 14:14 UTC, tsuyoshi628 requested changes

2020-09-06 14:14 UTC, tsuyoshi628 commented on api/seeders/20200903103937-test-users.js
>  module.exports = {
```
'use strict';
const bcrypt = require('bcrypt');
```
bcrypt読み込まないとエラー吐くと思われる

2020-09-06 14:14 UTC, tsuyoshi628 commented on api/setup.sh
> +npx sequelize-cli db:migrate:undo:all
わかんないけど、これっていけそう？？

2020-09-07 12:16 UTC, turunasi commented
@tsuyoshi628 
出来たよ.ついでにsetupスクリプトbinに突っ込んだ

2020-09-07 12:17 UTC, turunasi commented on api/setup.sh
> +npx sequelize-cli db:migrate:undo:all
対応した.動いてる

2020-09-08 05:27 UTC, tsuyoshi628 commented
> @tsuyoshi628
> 出来たよ.ついでにsetupスクリプトbinに突っ込んだ

おーいいね

2020-09-08 05:28 UTC, tsuyoshi628 approved these changes
いい感じ。

2020-09-08 05:29 UTC, merged