Feature/taira/credential#80
Piko-Piko-Pon-Taro/Remollege pull request #97
Opened 2020-09-07 14:18 UTC by pahalce

くれでんしゃる #80

2020-09-07 14:20 UTC, pahalce commented
@tsuyoshi628 @turunasi @tomoino

2020-09-08 05:16 UTC, tsuyoshi628 requested changes
どひゃ

2020-09-08 05:16 UTC, tsuyoshi628 commented on client/components/organisms/ProfileCard.vue
> +    // ActionButton: () => import('@/components/atoms/ActionButton'),
これ使ってなかったら消していいと思う。

2020-09-08 05:16 UTC, tsuyoshi628 commented on client/components/organisms/VideoArea.vue
> +          // .catch((err) => alert(err))
これいらないなら消していいかも

2020-09-08 05:16 UTC, tsuyoshi628 commented on client/store/auth.js
> +    const formData = new FormData()
これってlinterのせいで`let`から`const`に変えられちゃった感じ？🤔

2020-09-08 05:16 UTC, tsuyoshi628 commented on api/routes/video.js
> +require("dotenv").config();
できたらここじゃなくて`app.js`の1行目で読み込んで欲しい

2020-09-08 05:16 UTC, tsuyoshi628 commented on api/routes/video.js
> +const bodyParser = require("body-parser");
express標準のミドルウェアで処理してるのでいらないはず

2020-09-08 05:16 UTC, tsuyoshi628 commented on api/routes/video.js
> +router.use(bodyParser.urlencoded({ extended: true })); // support encoded bodies
express標準のミドルウェアで処理してるのでいらないはず

2020-09-08 05:16 UTC, tsuyoshi628 commented on api/routes/video.js
> +  );
ここってなにしてるの？？🤔

2020-09-08 05:16 UTC, tsuyoshi628 commented on api/routes/video.js
> +    res.status(400).send("Bad Request");
boomを使ってほしす

2020-09-08 05:16 UTC, tsuyoshi628 commented on api/routes/video.js
> +  res.send(credential);
boomを使ってほしす

2020-09-08 05:17 UTC, tsuyoshi628 commented on api/routes/video.js
> +const bodyParser = require("body-parser");
bodyParserの話です。

2020-09-08 05:18 UTC, tsuyoshi628 commented on api/routes/video.js
> +    res.status(400).send("Bad Request");
`res.status...`ってところです。

2020-09-08 05:18 UTC, tsuyoshi628 commented on api/routes/video.js
> +  res.send(credential);
`res.send...`ってところです。

2020-09-08 08:58 UTC, pahalce commented on api/routes/video.js
> +require("dotenv").config();
app.jsで.envつかってなくない？

2020-09-08 08:59 UTC, pahalce commented on api/routes/video.js
> +const bodyParser = require("body-parser");
そうなんか、けすわ

2020-09-08 09:00 UTC, pahalce commented on api/routes/video.js
> +  );
公式のやつそのままつかってるだけ笑

2020-09-08 09:01 UTC, pahalce commented on api/routes/video.js
> +    res.status(400).send("Bad Request");
boomってなんや

2020-09-08 09:02 UTC, pahalce commented on api/routes/video.js
> +  res.send(credential);
エラーのやつか

2020-09-08 09:03 UTC, pahalce commented on client/components/organisms/ProfileCard.vue
> +    // ActionButton: () => import('@/components/atoms/ActionButton'),
ここ俺かいたとこじゃないけどあとでつかうんじゃないかな、とりあえずけしちゃうか

2020-09-08 09:04 UTC, pahalce commented on client/store/auth.js
> +    const formData = new FormData()
あ、そうだわ
自分でいじった覚え全くない

2020-09-08 10:03 UTC, tsuyoshi628 commented on client/components/organisms/ProfileCard.vue
> +    // ActionButton: () => import('@/components/atoms/ActionButton'),
とりあえず使ってないなら消してよさそう。

2020-09-08 10:06 UTC, tsuyoshi628 commented on client/store/auth.js
> +    const formData = new FormData()
`let`にしといて、その行だけlinter無視するコメントアウト書いておいた方が良さそう。
```
alert('foo'); // eslint-disable-line
```
こんな感じで。

2020-09-08 10:07 UTC, tsuyoshi628 commented on api/routes/video.js
> +require("dotenv").config();
`app.js`で`require("dotenv").config();`読み込めば、全てのところで`process.env....`で.envファイルの中身読み込めるようになると思う。

2020-09-08 10:08 UTC, tsuyoshi628 commented on api/routes/video.js
> +const bodyParser = require("body-parser");
多分。一応動作確認はしてほしす

2020-09-08 10:08 UTC, tsuyoshi628 commented on api/routes/video.js
> +router.use(bodyParser.urlencoded({ extended: true })); // support encoded bodies
こちらも同様。

2020-09-08 10:10 UTC, tsuyoshi628 commented on api/routes/video.js
> +  );
もしかしたらセキュリティてきにあれかもしれない🤔

2020-09-08 10:10 UTC, tsuyoshi628 commented on api/routes/video.js
> +  );
わかんないけど。

2020-09-08 10:10 UTC, tsuyoshi628 commented on api/routes/video.js
> +  res.send(credential);
そうそう。
他のrouterを参考にしてもらえればと思います。

2020-09-08 10:12 UTC, tsuyoshi628 commented on api/routes/video.js
> +  res.send(credential);
と思ったけど、聞いてもらえればと思います。

2020-09-08 12:02 UTC, pahalce commented on client/components/organisms/VideoArea.vue
> +          // .catch((err) => alert(err))
これつぎエラーハンドりんぐやるからそっちにまとめるわ

2020-09-08 12:49 UTC, pahalce commented on api/routes/video.js
> +  );
けしました

2020-09-08 14:58 UTC, tsuyoshi628 approved these changes
![ヨシ](https://user-images.githubusercontent.com/42288506/92227244-f47ae080-eee0-11ea-9d72-b569cc302340.jpg)

2020-09-08 14:58 UTC, merged